PilzDE/psen_scan_v2

CMakeLists.txt

The `ScannerConfiguration` source file is currently added to the incorrect target. It must be added to a target a "level" lower, otherwise, the user of the `psen_scan_v2` lib has not all necessary sources available.

Fix incorrect source assignment

---

include/psen_scan_v2/udp_connection_state_machine.h

Will not call on_entry and on_exit of the state which caused trouble
using the rosconsole_bridge. The whole ros system would get
unresponsive.
Please merge before https://github.com/PilzDE/psen_scan_v2/pull/18

Use internal transition in state machine

---

include/psen_scan_v2/laserscan.h
include/psen_scan_v2/ros_scanner_node.h
src/laserscan.cpp
test/unit_tests/unittest_laserscan.cpp

This method was error-prone and not really necessary for publishing single frames.

Remove LaserScan::isNumberOfScansValid

---

include/psen_scan_v2/scanner_reply_msg.h
test/unit_tests/unittest_msg_decoder.cpp
test/unit_tests/unittest_scanner_reply_msg.cpp

This PR removes the error-prone separation of `ScannerReplyMsgType` and the corresponding OpCode values.

Consolidate raw OPCode value and ReplyMsgType

---

CMakeLists.txt
test/include/psen_scan_v2/async_barrier.h
test/include/psen_scan_v2/mock_udp_server.h
test/integration_tests/integrationtest_scanner_api.cpp
test/integration_tests/integrationtest_udp_client.cpp
test/unit_tests/unittest_scanner.cpp

This PR adds an integration-test which uses all "real" software components of the overall system and simulates the real hardware scanner with a mocked UDP server.
**Note:**
This PR results from the observation that changes to the code base can be made without detecting that the existing functionality was broken.
**Note:**
This PR requires the following PR's to be merged first (rebase this PR than => CI will be green):

Add Scanner-API integrationtest

---

test/unit_tests/unittest_scanner_controller.cpp

This PR removes the misleading unexpected call messages from gmock from `unittest_scanner_controller.cpp`

Remove misleading unexpected call messages from gmock

---

include/psen_scan_v2/start_request.h
test/unit_tests/unittest_scanner.cpp
test/unit_tests/unittest_tenth_of_degree.cpp

Check with
```
catkin_make -DCATKIN_ENABLE_CLANG_TIDY=True
catkin_make tests -DCATKIN_ENABLE_CLANG_TIDY=True
```

clang-tidy fixes

---

include/psen_scan_v2/monitoring_frame_msg.h
test/include/psen_scan_v2/udp_frame_dumps.h
test/integration_tests/integrationtest_scanner_api.cpp
test/unit_tests/unittest_monitoring_frame_msg.cpp
test/unit_tests/unittest_monitoring_frame_serialization.cpp

Add a CTOR to MonitoringFrameMsg. With this the usage of the raw hex dumps should be reduced in upcoming PRs.

Add CTor for MonitoringFrameMsg

---

include/psen_scan_v2/scanner_controller.h

Changes a debug lvl msg to info to notify the user of a successful start of the scanner.
This is in particular useful when the start was not successful right away.

Adds scanner started msg

---

include/psen_scan_v2/scanner_controller.h

Should fix the issue of a waning popping up on every shutdown.
Before (occasionally):
```bash
[ INFO] [1603090991.474239786]: Start scanner called.
[ INFO] [1603090991.477416409]: Scanner started successfully.
^C[rviz-3] killing on exit
[laser_scanner-2] killing on exit
[ INFO] [1603090995.474167950]: Stop scanner called.
[ WARN] [1603090995.474580951]: Received monitoring frame despite not waiting for it (in State 3)   // <-Not good
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```
After:
```bash
[ INFO] [1603090982.681571324]: Start scanner called.
[ INFO] [1603090982.683177099]: Scanner started successfully.
^C[rviz-3] killing on exit
[laser_scanner-2] killing on exit
[ INFO] …
```

Closes data udp connection on stop

---

include/psen_scan_v2/scanner_v2.h
src/scanner_v2.cpp
test/integration_tests/integrationtest_scanner_api.cpp

This PR tries to make the ScannerAPI tests more robust. Therefore,
- the ports are changed for every test,
- the Timeout test `testStartReplyTimeout()` is modified,
- the test `shouldThrowWhenStartIsCalledTwice()` is temporarily removed because there seems to be an error in the production code which needs to be fixed.

Improve robustness of ScannerAPI tests

---

include/psen_scan_v2/laserscan_conversions.h
include/psen_scan_v2/scan_range.h
src/laserscan.cpp
src/psen_scan_driver.cpp
test/unit_tests/unittest_laserscan.cpp
test/unit_tests/unittest_laserscan_conversions.cpp

Fixes an error
```
[ INFO] [1603792097.975607951]: Start scanner called.
[ WARN] [1603792097.977530696]: Received monitoring frame despite not waiting for it
[ INFO] [1603792097.978471639]: Scanner started successfully.
[ WARN] [1603792097.981032962]: The scanner reports an error: {Device: Master - Error in the External Device Monitoring (EDM1_ERR).}
psen_scan_v2_node: /usr/include/boost/msm/front/state_machine_def.hpp:209: void boost::msm::front::state_machine_def<Derived, BaseState>::exception_caught(const Event&, FSM&, std::exception&) [with FSM = boost::msm::back::state_machine<psen_scan_v2::scanner_protocol::ScannerProtocolDef>; Event = psen_scan_v2::scanner_protocol::scanner_events::RawMonitoringFrameReceived; Derived = psen_scan_v2::scanner_protocol::ScannerProtocolDef; BaseState = …
```

Fixes failure when smaller scan range

---

include/psen_scan_v2/angle_conversions.h
include/psen_scan_v2/scan_range.h
include/psen_scan_v2/tenth_of_degree.h
src/monitoring_frame_deserialization.cpp
src/start_request.cpp
test/unit_tests/unittest_scan_range.cpp
test/unit_tests/unittest_start_request.cpp
test/unit_tests/unittest_tenth_degree_conversion.cpp
test/unit_tests/unittest_tenth_of_degree.cpp

This essentially replaces `uint16_t` by `int16_t` such that the class `TenthOfDegree` and the angle conversions support negative values.
The protocol does not specify if the 16bit angles are signed or unsigned. But, concerning the scan range, it has to be in [0, 2750], such that it makes no difference if we use signed or unsigned type in (de)serialization.

Use signed integer type for representing angles in tenth degree

---

test/hw_tests/hwtest_readme.md
test/hw_tests/hwtest_scan_compare.test
test/include/psen_scan_v2/laserscan_validator.h

- Choose start- and end-angle such that environment is not expected to change
- remove `hztest` for now, since the publishing frequency varies with the scan range
- fix small bug in `laserscan_validator.h` which appeared through this change

Set start- and end-angle for acceptance test

---

CMakeLists.txt

Since rosbag is only needed with the HW tests it should be defined as a dep only if `-DENABLE_HARDWARE_TESTING=ON` is set.
See http://build.ros.org/job/Mdev__psen_scan_v2__ubuntu_bionic_amd64/18/console
```
14:26:42 -- Could NOT find rosbag (missing: rosbag_DIR)
14:26:42 -- Could not find the required component 'rosbag'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
14:26:42 CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
14:26:42   Could not find a package configuration file provided by "rosbag" with any
14:26:42   of the following names:
14:26:42 
14:26:42     rosbagConfig.cmake
14:26:42     rosbag-config.cmake
14:26:42 
14:26:42   Add the …
```

Fix dep on rosbag

---

include/psen_scan_v2/diagnostics.h
include/psen_scan_v2/monitoring_frame_msg.h
include/psen_scan_v2/start_request.h

This is a preparation for a noetic release. Since the default distro for noetic is Ubuntu 20 which comes with gcc 9 this error gets detected. (Was wrong even before but gcc7 does not detect it)
Replaces #97

Fix friend declaration

---

include/psen_scan_v2/default_parameters.h
include/psen_scan_v2/scan_range.h
include/psen_scan_v2/scanner_config_builder.h
include/psen_scan_v2/scanner_configuration.h
include/psen_scan_v2/scanner_v2.h
src/psen_scan_driver.cpp
src/scanner_configuration.cpp
src/scanner_v2.cpp
test/integration_tests/integrationtest_ros_scanner_node.cpp
test/integration_tests/integrationtest_scanner_api.cpp
test/unit_tests/unittest_scanner_configuration.cpp
test/unit_tests/unittest_start_request.cpp

This PR moves the scanner ports to the `ScannerConfiguration` class. Because the number of  parameters of the `ScannerConfiguration` reached a critical "mass", the `ScannerConfigurationBuilder` is introduced.

Move Scanner port to ScannerConfiguration

---

test/integration_tests/integrationtest_scanner_api.cpp

This is caused by https://github.com/PilzDE/pilz_robots/commit/e9a0b37f7104f645e3cba6f2636bfb375d6d7e37 but was possibly not detected due to using the system installed headers which is fixed in https://github.com/PilzDE/pilz_robots/pull/466
A double release of pilz_robots and psen_scan_v2 is required to fix the situation.

Adapt to new logger API

---

test/include/psen_scan_v2/udp_frame_dumps.h
test/unit_tests/unittest_laserscan_conversions.cpp

42f067d89b2edd289449b8bf3ad5ce15abe59d17 introduced some clang-format errors

Apply fixes from clang-format

---

include/psen_scan_v2/scanner_state_machine.h
include/psen_scan_v2/scanner_state_machine_def.h

These changes partly fix the doxygen documentation.
Before, doxygen could not find the file `scanner_state_machine_def.h`.
With this change the file is included in the docu. Now there are other warnings, because it contains macros which not being expanded by doxygen.

Move #include out of namespace scope

---

CHANGELOG.rst
README.md
include/psen_scan_v2/default_parameters.h
src/psen_scan_driver.cpp

These changes allow the user to start the psen_scan driver without specifying the udp ports.

Make specifying ports optional

---

include/psen_scan_v2/ros_scanner_node.h

These changes Fix #124
In a test we can not wait deterministically for the execution of the body of the while-loop before we terminate the node.

Exclude line which can not be reached deterministically

---

include/psen_scan_v2/scan_range.h
include/psen_scan_v2/start_request.h

This PR improves the code readability by removing implicit creation of invalid `ScanRange` objects.

Make invalid ScanRange creation explicit

---

CMakeLists.txt

Some of the dependent packages/libraries do not need to be passed along since we do not export our header files.

Remove exports on dependent packages

---

include/psen_scan_v2/logging.h
test/integration_tests/integrationtest_scanner_api.cpp
test/unit_tests/unittest_logging.cpp

These changes allow the user to set a log level via `console_bridge::setLogLevel()`.
Needed for #107

Enable setting log level in console bridge

---

include/psen_scan_v2/scanner_configuration.h
src/scanner_configuration.cpp
test/unit_tests/unittest_scanner_configuration.cpp

In addition to e8f88cd3d103a5daf77df4aff8f8da9a1ae1a4c0, these changes  allow the user to build a `ScannerConfiguration `without setting the ports.
#107 will make use of it.

Use defaults ports in ScannerConfiguration

---

CMakeLists.txt

The hardware test fails to compile on the main branch (91104569fdeb31e229fa171f408eb26a085bbdcf)
Full log: [hwtest_log.txt](https://github.com/PilzDE/psen_scan_v2/files/5796777/hwtest_log.txt)

Fix compilation of hwtest_scan_compare

---

standalone/test/unit_tests/unittest_raw_processing.cpp

The data read from the ostringstream must be copied byte-wise not in chunks of `sizeof(TypeParam)`.
This show up in failing tests on https://build.ros.org/job/Ndev_db__psen_scan_v2__debian_buster_amd64/15/ and
also explains why it worked with `TypeParam` == uint8_t

Fix undefined behaviour from unittest_raw_processing

---

.github/workflows/ci_action_standalone.yml
standalone/CMakeLists.txt
standalone/README.md

if library version >= 1.69 is available there is no need to use the `system` library any longer.
This simplifies windows build(s) in the future, see https://www.boost.org/doc/libs/1_75_0/more/getting_started/windows.html

boost header-only build

---

standalone/include/psen_scan_v2_standalone/scanner_reply_serialization_deserialization.h
standalone/include/psen_scan_v2_standalone/scanner_v2.h
standalone/include/psen_scan_v2_standalone/start_request.h
standalone/src/scanner_reply_serialization_deserialization.cpp
standalone/src/scanner_v2.cpp
standalone/src/start_request.cpp

reported by include-what-you-use and forward-declare ScannerConfiguration
The full log is attached:
[iwyu.out.txt](https://github.com/PilzDE/psen_scan_v2/files/5881341/iwyu.out.txt)
I've cleaned the header files as suggested. If anyone wants to additionally clean up the cpp files, see the output above.
These changes clean up included headers.

fix some headers

---

.github/workflows/ci_action_win_standalone.yml

* let cmake generate the build dir using -B
* skip debug dir listings
* skip -DCMAKE_BUILD_TYPE only relevant during build
and ignored by VS2019 generator

try several simplifications

---

test/hw_tests/hwtest_scan_compare.cpp

Boost filesystem was only used in one test to check the existence of a file which would be opened by rosbag throwing. I think catching is the better solution.

Remove dep on boost::filesystem

---

.github/workflows/ci_action_win_standalone.yml

fixup the CI. If putting the `include(ctest)` into the conditional block, we have to also enable this block for windows.

fixup CI for standalone branch

---

README.md

The table of contents was broken - while fixing it I also re-ordered the subsections. What do you think?
* Put C++ library at the beginning
* group parameters and their explanation under 'Usage'
* group build status, branching and test concept as new section 'developer information'
and create TOC including missing paragraphs with the help of https://ecotrust-canada.github.io/markdown-toc/

Reorder Readme sections

---

README.md

that are only advanced usage documented in the launch file comments
For easier getting started the expert parameters are documented inside the launch file only. This makes it much easier, to find the paramters that are meant to change for first-time-users.

drop expert parameters

---

README.md

Remove the unneccessary optional parameters from the usage example in the readme

Removed host_ip and port from roslaunch command

---

CMakeLists.txt

Fixes an error introduced in a66adf5797e7d1e57683adbc1761a83e398d558d, see https://build.ros.org/job/Mdev__psen_scan_v2__ubuntu_bionic_amd64/71
Release is overdue ...
None

Add missing find_package() calls to CMakeLists.txt

---

standalone/include/psen_scan_v2_standalone/data_conversion_layer/start_request.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/start_request_serialization.h
standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h
standalone/src/data_conversion_layer/start_request_serialization.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_start_request.cpp

Actually occured while preparing for https://github.com/PilzDE/psen_scan_v2/pull/185
where a error is printed by `rosdoc_lite`
```
/home/alex/catkin_ws_rosdoc_ci/src/psen_scan_v2/standalone/src/data_conversion_layer/start_request_serialization.cpp:124: warning: no uniquely matching class member found for 
RawData psen_scan_v2_standalone::data_conversion_layer::data_conversion_layer::start_request::serialize(const data_conversion_layer::start_request::Message &msg)
```
Nevertheless using default arguments should be the better way here.

Use default args for start_request::serialize

---

standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h

Removes warnings
```
/home/alex/catkin_ws_rosdoc_ci/src/psen_scan_v2/standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h:53: warning: documented symbol 'void psen_scan_v2_standalone::protocol_layer::ScannerProtocolDef::Idle::on_exit' was not declared or defined.
/home/alex/catkin_ws_rosdoc_ci/src/psen_scan_v2/standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h:61: warning: documented symbol 'void psen_scan_v2_standalone::protocol_layer::ScannerProtocolDef::WaitForStartReply::on_entry' was not declared or defined.
/home/alex/catkin_ws_rosdoc_ci/src/psen_scan_v2/standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h:69: warning: documented symbol 'void …
```

Remove warnings from doxygen for boost::msm

---

test/include/psen_scan_v2/laserscan_validator.h

Needs #193 
With this `colcon build --cmake-args "-DENABLE_HARDWARE_TESTING=ON"` 
results in 
```
/home/alex/catkin_ws_psen_scan_v2_only/src/psen_scan_v2/test/include/psen_scan_v2/laserscan_validator.h:43:113: error: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second: [-Werror]
43 |                                                                                      scan.getScanResolution() * i);
| 
...
/home/alex/catkin_ws_psen_scan_v2_only/src/psen_scan_v2/test/include/psen_scan_v2/laserscan_validator.h:59:78: error: base operand of ‘->’ has non-pointer type ‘const LaserScan’ {aka ‘const sensor_msgs::LaserScan_<std::allocator<void> >’}
59 | …
```

Fix hardware tests compile errors

---

CHANGELOG.rst
CMakeLists.txt
README.md
launch/psen_scan_v2.launch
rosdoc.yaml
src/psen_scan_driver.cpp
standalone/include/psen_scan_v2_standalone/configuration/default_parameters.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/laserscan_conversions.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/monitoring_frame_deserialization.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/raw_processing.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/start_request.h
standalone/include/psen_scan_v2_standalone/protocol_layer/scan_buffer.h
standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine.h
standalone/include/psen_scan_v2_standalone/scanner_config_builder.h
standalone/include/psen_scan_v2_standalone/scanner_configuration.h
standalone/main.cpp
standalone/src/data_conversion_layer/start_request.cpp
standalone/src/data_conversion_layer/start_request_serialization.cpp
standalone/test/include/psen_scan_v2_standalone/util/integrationtest_helper.h
standalone/test/integration_tests/api/integrationtest_scanner_api.cpp
standalone/test/unit_tests/configuration/unittest_scanner_configuration.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_start_request.cpp

These changes add: 
- the possibility to change the **resolution** of the scanner on startup (**default will change from 0.2 to 0.1** with this PR)
- the possibility to disable/enable the **intensities** on startup (**default will change from true to false** with this PR)
- when scan range changes are implemented as well
- needs minor version change

Add option to modify resolution and intensities

---

test/hw_tests/hwtest_scan_compare.cpp

Before this change the hardwaretest wouldn't subscribe to the topic. Tbh didn't have the time so far to give it a deeper thought.

Fixes HWTest not subscribing to topic

---

test/hw_tests/config/big_resolution.yaml
test/hw_tests/config/default.yaml
test/hw_tests/config/subrange.yaml
test/hw_tests/config/with_intensities.yaml
test/hw_tests/hwtest_publish.test
test/hw_tests/hwtest_scan_range.test

The tests need to read the environment variables SENSOR_IP and HOST_IP in order to be able using `industrial_ci` used by the hardware test.
Note so happy that ca624111d1f30d0665bcb7e56eda97a579284457 is needed by otherwise it seems that sometimes old messages from a previous test run are checked.

Enable hwtests with industrial_ci

---

.github/workflows/ci_action_noetic_binary.yml
test/integration_tests/integrationtest_ros_scanner_launch.test

These changes help the developer preventing issues like #169.
The `debian` job builds the debian binary and stores it on GitHub.
The `launch-check` job installs the debian package in a fresh container and executes a simple launch test.

Add workflow for testing launch with installed debian-package

---

CHANGELOG.rst
standalone/include/psen_scan_v2_standalone/data_conversion_layer/monitoring_frame_deserialization.h
standalone/src/data_conversion_layer/monitoring_frame_deserialization.cpp
standalone/test/src/data_conversion_layer/monitoring_frame_serialization.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_monitoring_frame_serialization_deserialization.cpp

Some measurement values from the laser scanner have special meanings:
59956: no reflective signal arrived,
59958: a reflective signal arrived, but it was too late (according to our time window)
both should be published as +infinity
Before the PR the measurments are published as described above. And after the PR +infinity values are published instead of 59956 or 59958.

Infinity treatment

---

standalone/test/integration_tests/api/integrationtest_scanner_api.cpp

The changes Fix the gmock warnings in tests.
There where two causes:
- The creation of the scanner already made some mock calles, before the debug logs where expected.
- Laser Scan Callbacks have not been expected.

Fix mock warnings in api integration tests

---

CHANGELOG.rst
README.md
config/config.rviz
launch/bringup.launch
test/hw_tests/hwtest_publish.test
test/hw_tests/hwtest_scan_compare.cpp
test/hw_tests/hwtest_scan_range.py
test/hw_tests/hwtest_scan_range.test
test/integration_tests/integrationtest_ros_scanner_launch.test

These changes allow the system integrator to bringup the scanner from his custom launch file.
The tutorials are changed accordingly: https://github.com/PilzDE/pilz_tutorials/pull/29
To avoid confusion of the user the prefix of the node name is changed to match the prefix of the LaserScan-topic. In detail setting the prefix implies the following namings:
- node: `<prefix>_node`
- topic: `<prefix>_node/scan`
- tf frames: `<prefix>`, `<prefix>_mount_link`, `<prefix>_scan`
asap
None

Introduce bringup.launch for starting only the scanner node

---

CHANGELOG.rst
README.md
config/config.rviz
launch/bringup.launch
launch/psen_scan_v2.launch
src/psen_scan_driver.cpp
test/hw_tests/config/big_resolution.yaml
test/hw_tests/config/default.yaml
test/hw_tests/config/subrange.yaml
test/hw_tests/config/with_intensities.yaml
test/hw_tests/hwtest_publish.test
test/hw_tests/hwtest_scan_compare.cpp
test/hw_tests/hwtest_scan_range.py
test/hw_tests/hwtest_scan_range.test
test/integration_tests/integrationtest_ros_scanner_launch.test

These changes fix the naming convention introduced in c5f8f385a901cfc2b28b8a34c83ca561a1ef9c36 such that the node name equals the tf prefix.

Apply convention node name equals tf prefix

---

standalone/README.md

With this PR I set the versions within readme to be the same as https://github.com/PilzDE/psen_scan_v2/blob/main/.github/workflows/ci_action_win_standalone.yml

Clarifying tested versions for windows build

---

test/hw_tests/hwtest_readme.md
test/hw_tests/hwtest_scan_compare.cpp
test/hw_tests/hwtest_scan_compare.test

These changes make `hwtest_scan_compare` run in industrial_ci. Fixes #205 
Fix hwtest_scan_compare:
* Include bringup.launch
* Set unique udp port for data connection
* Only start laserscan validation when connected on topic
* Omit using SetUpTestSuite()
Due to google/googletest#247
Can be reverted once googletest version is at least 1.11.0
Update hwtest_readme.md:
* Update forwarded udp ports
* Add description for running test with reference scan using industrial_ci

Fix hwtest_scan_compare

---

.github/workflows/ci_action_standalone.yml
.github/workflows/ci_action_win_standalone.yml

Here is an example output with a test failure:
https://github.com/martiniil/psen_scan_v2/runs/3408852133

Enable output on failure for standalone ci jobs

---

CHANGELOG.rst
CMakeLists.txt
standalone/include/psen_scan_v2_standalone/laserscan.h
standalone/src/laserscan.cpp
standalone/test/include/psen_scan_v2_standalone/util/integrationtest_helper.h
standalone/test/unit_tests/api/unittest_laserscan.cpp

These changes avoid confusion about the LaserScan equality operator.
It is not clear, if this operator should compare the timestamps and if it really should check measurements/intensities (double values!) for equality. So we remove it. In our code it is only used in tests where it can by replaced by a more descriptive matcher.
note: My first attempt of using Pointwise(DoubleEq(), ...) as matcher did not work with the googletest version on bionic.
Changes in detail:
- Refactor laserscan comparison
- Add ostream operator for better output in case of test failure

Refactor laserscan comparison

---

CMakeLists.txt
standalone/CMakeLists.txt
standalone/src/data_conversion_layer/start_request_serialization.cpp

This PR changes the default build type to be a release build.
This way the tests gets executed in release build which is prefarable specially for hardware tests.

Make release build the default

---

standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h

Removes unnecessary calls to `fmt::format`
---
<details>
</details>

Remove unneccessary fmt::format

---

standalone/test/unit_tests/communication_layer/unittest_udp_client.cpp

Fixes a clash in the port range of `unittest_udp_client` and `integrationtest_scanner_api`. 
---
<details>
</details>

Fix test ports clash

---

standalone/include/psen_scan_v2_standalone/communication_layer/udp_client.h
standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h
standalone/src/scanner_v2.cpp
standalone/test/integration_tests/api/integrationtest_scanner_api.cpp
test/include/psen_scan_v2/laserscan_validator.h

These changes Fix #241 by changing the scanner deconstruction.
These changes solve the problem since:
- `stop()` on the state machine does not prevent further `process_event` thus it is better to transition into the defined `Stop`-State. I.e. we (currently) always require a call to `ScannerV2::stop()`. To avoid receiving more messages the `io_service` needed to be stopped(). It seems that going into destruction while receiving messages which are redirected to `handleReceiveMessage` is a bad idea...
- Inside the tests the member order the mock is put at the end so that is gets destroyed first. This in combination with the above seems to stabilize the test.
---
<details>
_Unstrike the text below to enable automatic hardware tests if available. Otherwise use …

Fix scanner deconstruction

---

standalone/include/psen_scan_v2_standalone/util/tenth_of_degree.h
standalone/test/include/psen_scan_v2_standalone/util/integrationtest_helper.h
standalone/test/unit_tests/configuration/unittest_scanner_configuration.cpp
standalone/test/unit_tests/util/unittest_tenth_of_degree.cpp

Removes the imho unnecessary member function `constexpr operator uint16_t() const` from `TenthOfDegree`.
Mathematical operations should talk place within the type as long as possible and convertion should be done explicitly at the last moment possible.

Minor improvement of TenthOfDegree

---

CHANGELOG.rst
CMakeLists.txt
package.xml
test/integration_tests/integrationtest_ros_scanner_node.cpp

These changes remove the pilz_testutil dependency in favour of the standalone util barrier
---
<details>
It's not urgent.
</details>

Removing usage and dependancy of pilz_testutils

---

standalone/src/data_conversion_layer/scanner_reply_serialization_deserialization.cpp

This "TODO" originated in the `RawType` being of fixed size, which is no longer the case.
Original code:
https://github.com/pilzde/psen_scan_v2/blob/b6b6f3c63b3a126a8e2746cd7d6733daa8885e8a/include/psen_scan_v2/reply_msg_from_scanner.h
```
using RawType = std::array<char, REPLY_MSG_FROM_SCANNER_SIZE>;
```
```
inline ReplyMsgFromScanner::RawType ReplyMsgFromScanner::toCharArray()
{
std::ostringstream os;
uint32_t crc{ calcCRC(*this) };
os.write((char*)&crc, sizeof(uint32_t));
os.write((char*)&reserved_, sizeof(uint32_t));
os.write((char*)&opcode_, sizeof(uint32_t));
os.write((char*)&res_code_, sizeof(uint32_t));
ReplyMsgFromScanner::RawType ret_val{};
// TODO check limits
std::string data_str(os.str());
assert(data_str.length() == REPLY_MSG_FROM_SCANNER_SIZE && "Message data of start reply …
```

Remove outdated todo

---

standalone/README.md

ROS noetic docu obviously moved to a subdirectory.

fix broken links in standalone Readme.md

---

standalone/test/include/psen_scan_v2_standalone/util/expectations.h
standalone/test/integration_tests/api/integrationtest_scanner_api.cpp

**edit: hold until we know if `scanner.start()`/`stop()` persist**
We expect that scanner.start() and stop() do not throw, so this was missing
These changes hopefully shed some light on #262.
---
<details>
</details>

Check for valid future and exception of scanner start()/stop()

---

src/psen_scan_driver.cpp
standalone/include/psen_scan_v2_standalone/scanner_config_builder.h
standalone/main.cpp
standalone/test/integration_tests/api/integrationtest_scanner_api.cpp
standalone/test/unit_tests/configuration/unittest_scanner_configuration.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_start_request.cpp
test/hw_tests/hwtest_scan_compare_standalone.cpp
test/hw_tests/hwtest_timestamp_standalone.cpp
test/integration_tests/integrationtest_ros_scanner_node.cpp

IP address is the only mandatory argument, so make it a param of the constructor to
always have a valid config. The builder is implicitly convertible into a configuration,
to save the user from typing build() in every situation.
This simplifies the main.cpp into more readable and convenient:
```
auto config = ScannerConfigurationBuilder(SCANNER_IP).scanRange(ScanRange{ ... });
ScannerV2 scanner(config, laserScanCallback);
```
---
<details>
</details>

convenience usage of ScannerConfiguration

---

CHANGELOG.rst
include/psen_scan_v2/ros_scanner_node.h
test/integration_tests/integrationtest_ros_scanner_node.cpp

Removes the latched flag from active_zoneset topic since internally it does not hold back similar states anyway.
---
<details>
</details>

Remove latched from active zoneset topic

---

test/hw_tests/config/big_resolution.yaml
test/hw_tests/config/subrange.yaml
test/hw_tests/hwtest_scan_range.py
test/hw_tests/hwtest_scan_range.test

Observed in #270: the `hwtest_scan_range` relied on the input angles/resolution being multiple of tenth degrees.
**Addition**: Fix problem that test result gets overwritten by runs with different config. This led to false test results reported by the PilzHardwareTestBot, see comments below.
---
<details>
</details>

Fix hwtest_scan_range for angles which get rounded

---

CHANGELOG.rst
test/hw_tests/hwtest_zoneset_switching.cpp
test/include/psen_scan_v2/ros_integrationtest_helper.h
test/include/psen_scan_v2/subscriber_mock.h
test/integration_tests/integrationtest_active_zoneset_node.cpp
test/integration_tests/integrationtest_config_server_node.cpp
test/integration_tests/integrationtest_ros_scanner_node.cpp

These changes unify three SubScriberMocks and move the unified class to ros_integrationstest_helper.h
</details>

Unify SubscriberMocks

---

CHANGELOG.rst
standalone/include/psen_scan_v2_standalone/configuration/scanner_ids.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/start_request.h
standalone/src/data_conversion_layer/start_request_serialization.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_monitoring_frame_diagnostic_message.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_monitoring_frame_msg.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_monitoring_frame_serialization_deserialization.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_start_request.cpp

This changes all occurrences of slave to subscriber. 
It is the new name for the slave models of PSENscan.
At important places comments were added to avoid confusion with the ros-internal meaning of subscriber.
---
<details>
</details>

Renaming Slave to Subscriber 

---

CMakeLists.txt
standalone/CMakeLists.txt
standalone/include/psen_scan_v2_standalone/data_conversion_layer/io_pin_data.h
standalone/include/psen_scan_v2_standalone/io_state.h
standalone/src/io_state.cpp

Internal refactoring: These changes prepare #301, where we move parts of the `IOState` implementation to a separate header.

Move IOState implementation to io_state.cpp

---

include/psen_scan_v2/ros_scanner_node.h
standalone/include/psen_scan_v2_standalone/io_state.h
standalone/include/psen_scan_v2_standalone/util/format_range.h

These changes Fix hopefully the build error on the Ros build farm:
https://build.ros.org/job/Mbin_ubv8_uBv8__psen_scan_v2__ubuntu_bionic_arm64__binary/37/console
We could not reproduce this error locally so we could only gues the reason and fix based on the information provided.
Alternatives to this approach:
- Using ostream operator for PinState in Log of changed states.
Would result in something like "PinState(id = 1, name = Zone Bit 1, state = false)" rather than "Zone Bit 1 = false"
- Changing ostream operator.
Current formating would remove id from ostream and therefore would be less descriptive.
- Find some fmt format range possibility with lambda .
Has to work with fmt-4.0 and with what ever gcc version the buildfarm uses for melodic builds.
---
<details>
<summary>PR …

Separate Pin formating and revert formatRange lambda usage

---

CHANGELOG.rst
standalone/include/psen_scan_v2_standalone/data_conversion_layer/io_constants.h
standalone/test/unit_tests/data_conversion_layer/unittest_io_pin_data.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_io_state_conversions.cpp
test/integration_tests/integrationtest_ros_scanner_node.cpp
test/unit_tests/unittest_io_state_rosconversions.cpp

Removes zoneset bits from IO data since its redundant to the active zoneset field
---
<details>
</details>

Remove zoneset bits and update tests

---

README.md
src/config_server_node.cpp

Adds a warning to the readme and config server node to inform the user about the possible mismatch of the loaded config and the one on the connected hardware.
---
<details>
</details>

Inform about missing configuration confirmation

---

package.xml

* Adds urls
* Fixes missing field in http://wiki.ros.org/psen_scan_v2

Add author and urls to package.xml

---

.github/workflows/ci_action_melodic.yml
.github/workflows/ci_action_noetic.yml

*Jobs using clang-tidy will use clang
*This way the other builds remain gcc builds

Add clang-tidy as separate job

---

.github/workflows/ci_action_win_standalone.yml
standalone/README.md

These changes fix latest build errors on windows-ci-standalone.
See:
https://github.com/PilzDE/psen_scan_v2/tree/main/standalone#get-started-on-windows

CI: use windows-2019 environment
