PilzDE/psen_scan_v2

include/psen_scan_v2/angle_conversions.h
src/start_request.cpp
test/unit_tests/unittest_start_request.cpp

feature/new_firmware Set master resolution to the maximum 0.1deg

---

CMakeLists.txt
include/psen_scan_v2/logging.h
include/psen_scan_v2/raw_processing.h
include/psen_scan_v2/scanner_controller.h
include/psen_scan_v2/udp_client.h
package.xml
src/monitoring_frame_msg.cpp

For more infos on libfmt see https://github.com/fmtlib/fmt

Use libfmt for printing

---

CMakeLists.txt
include/psen_scan_v2/controller_state_machine.h
include/psen_scan_v2/ros_parameter_handler.h
include/psen_scan_v2/scanner_controller.h
include/psen_scan_v2/udp_connection_state_machine.h
src/controller_state_machine.cpp
test/unit_tests/unittest_controller_state_machine.cpp
test/unit_tests/unittest_scanner_controller.cpp

Add action handle_monitoring_frame

---

include/psen_scan_v2/monitoring_frame_msg.h
test/integration_tests/integrationtest_scanner_api.cpp
test/unit_tests/unittest_monitoring_frame_msg.cpp

Add print functionality for MonitoringFrameMsg

---

include/psen_scan_v2/scanner_state_machine.h
include/psen_scan_v2/scanner_state_machine.hpp
test/integration_tests/integrationtest_scanner_api.cpp

This was broken by 43a790317cd7589576e33356d25b17ff67272edb

Notify user about start retry

---

include/psen_scan_v2/udp_client.h

This PR fixes the problem of the sporadic deadlocks in the `UdpClient::startAsyncReceiving()` method. At the same time the PR fixes the bug that the received flag is not reset, after it was used.

Fix sporadic deadlock in UdpClient::startAsyncReceiving()

---

test/integration_tests/integrationtest_scanner_api.cpp

Due to the fact that the empty monitoring frame test sometimes hangs, I redesigned the test a little bit. I'm not sure why the original test stopped sporadically. The improved version however, works even if stress tested and is much more faster.

Improve sporadically hanging empty msg test in scanner api test

---

include/psen_scan_v2/scanner_v2.h
src/scanner_v2.cpp
test/integration_tests/integrationtest_scanner_api.cpp

This PR tries to remedy the issues which appear when `ScannerV2::start()` is called more than once.

Fix multi Scanner::start() issues

---

include/psen_scan_v2/diagnostics.h
test/unit_tests/unittest_monitoring_frame_diagnostic_message.cpp

Splits the internal communication problem into 2 internal error bits which should fix the configuration missing error.

Adds missing error bit

---

CMakeLists.txt
include/psen_scan_v2/complete_scan_validator.h
include/psen_scan_v2/start_request.h
src/start_request.cpp
src/start_request_serialization.cpp
test/unit_tests/unittest_scanner_reply_msg.cpp

This PR resolves some clang-tidy errors that appeared in #103
The fixes are split out for better clarity.

Fix clang tidy errors

---

CHANGELOG.rst
CMakeLists.txt
include/psen_scan_v2/format_range.h
include/psen_scan_v2/logging.h
include/psen_scan_v2/raw_processing.h
include/psen_scan_v2/scanner_state_machine.h
include/psen_scan_v2/scanner_state_machine.hpp
package.xml
src/monitoring_frame_deserialization.cpp
src/monitoring_frame_msg.cpp
test/hw_tests/hwtest_scan_compare.cpp
test/include/psen_scan_v2/dist.h
test/include/psen_scan_v2/laserscan_validator.h
test/unit_tests/unittest_monitoring_frame_msg.cpp

Directly use fmt lib instead of rosfmt

---

include/psen_scan_v2/laserscan.h
include/psen_scan_v2/laserscan_conversions.h
include/psen_scan_v2/monitoring_frame_deserialization.h
include/psen_scan_v2/monitoring_frame_msg.h
src/laserscan.cpp
src/monitoring_frame_deserialization.cpp
src/monitoring_frame_msg.cpp
test/include/psen_scan_v2/udp_frame_dumps.h
test/src/monitoring_frame_serialization.cpp
test/unit_tests/unittest_laserscan_conversions.cpp
test/unit_tests/unittest_laserscan_ros_conversions.cpp
test/unit_tests/unittest_monitoring_frame_msg.cpp

https://www.linguee.de/englisch-deutsch/uebersetzung/measure.html

Spelling measurements

---

test/include/psen_scan_v2/mock_console_bridge_output_handler.h
test/integration_tests/integrationtest_scanner_api.cpp
test/integration_tests/integrationtest_udp_client.cpp
test/unit_tests/unittest_raw_processing.cpp
test/unit_tests/unittest_ros_parameter_handler.cpp

These changes allow the maintainer to easily split ROS-dependent and -independent parts of the package.

Make all tests ROS independent, which should be

---

CMakeLists.txt
test/unit_tests/unittest_raw_processing.cpp

Just some minor fixes I discovered by chance.

Minor fixes

---

include/psen_scan_v2/scanner_state_machine_def.h

Omit message if diagnostics vector is empty

---

standalone/include/psen_scan_v2_standalone/scanner_config_builder.h
standalone/src/start_request_serialization.cpp

These changes should add a working ci for both windows and linux for the standalone lib

Add windows ci

---

standalone/include/psen_scan_v2_standalone/scanner_config_builder.h
standalone/include/psen_scan_v2_standalone/stop_request_serialization.h
standalone/src/start_request_serialization.cpp

Adapt endianess for standalone windows lib

---

.github/workflows/ci_action_win_standalone.yml
standalone/CMakeLists.txt
standalone/test/integration_tests/integrationtest_scanner_api.cpp
standalone/test/integration_tests/integrationtest_udp_client.cpp
standalone/test/unit_tests/unittest_monitoring_frame_serialization_deserialization.cpp
standalone/test/unit_tests/unittest_scanner_configuration.cpp
standalone/test/unit_tests/unittest_start_request.cpp
standalone/test/unit_tests/unittest_udp_client.cpp

These changes add test runs to the win standalon ci workflow

Add first test for standalone

---

standalone/README.md
standalone/include/psen_scan_v2_standalone/scanner_v2.h

These changes fix some links in the documentation.

Fix some links in the docu

---

standalone/include/psen_scan_v2_standalone/communication_layer/udp_client.h
standalone/test/include/psen_scan_v2_standalone/communication_layer/mock_udp_client.h

The timeout was removed with d67bf5f

Remove artefacts of UdpClient timeout

---

CHANGELOG.rst
src/psen_scan_driver.cpp
standalone/include/psen_scan_v2_standalone/configuration/scan_range.h
standalone/include/psen_scan_v2_standalone/configuration/scanner_config_builder.h
standalone/include/psen_scan_v2_standalone/configuration/scanner_configuration.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/start_request.h
standalone/main.cpp
standalone/src/configuration/scanner_configuration.cpp
standalone/test/integration_tests/api/integrationtest_scanner_api.cpp
standalone/test/unit_tests/configuration/unittest_scanner_configuration.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_start_request.cpp
standalone/test/unit_tests/util/unittest_scan_range.cpp
test/integration_tests/integrationtest_ros_scanner_node.cpp

This pull request addresses issue [#130](https://github.com/PilzDE/psen_scan_v2/issues/130)

Rename DefaultScanRange to ScanRange

---

.github/workflows/ci_action_win_standalone.yml
standalone/CMakeLists.txt
standalone/CMakeLists.txt.in

Builds gtest as part of the standalone project as suggested by google. See https://github.com/google/googletest/blob/master/googletest/README.md
This is a preparation for a following PR using this the also run the tests on the linux standalone job.

Build gtest as part of the project. Closes #150

---

.github/workflows/ci_action_win_standalone.yml

These changes Fix #172 
Next release is fix of #169
None

Manually fetch boost (header-only)

---

standalone/README.md

There is no Developer Console in Visual Studio. Only Developer Command Prompt

Fix naming in Readme

---

src/psen_scan_driver.cpp

Fixes #175 by implementing it the straight forward way.
_Checked with 32-bit Ubuntu 18 armhf_

Minor restructuring. Closes #175

---

.github/workflows/ci_action_todo.yml

Enables https://github.com/marketplace/actions/actions-todo-bot to check for uncheck todos in the PR description.
Needs https://github.com/PilzDE/.github/pull/17 to fully work.

Add action for pull request todos

---

CHANGELOG.rst
standalone/include/psen_scan_v2_standalone/data_conversion_layer/laserscan_conversions.h
standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine.h
standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h
standalone/test/integration_tests/api/integrationtest_scanner_api.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_laserscan_conversions.cpp

Possible fix for 
https://github.com/PilzDE/psen_scan_v2/issues/182
https://github.com/PilzDE/psen_scan_v2/issues/181

Fix issues with smaller angle ranges than default range

---

rosdoc.yaml
standalone/include/psen_scan_v2_standalone/communication_layer/udp_client.h

Preparation for https://github.com/PilzDE/psen_scan_v2/pull/185
Minor fixes. Without this the following issues would appear:
```
/home/alex/catkin_ws_rosdoc_ci/src/psen_scan_v2/README.md:1: warning: found more than one \mainpage comment block! (first occurrence: /home/alex/catkin_ws_rosdoc_ci/src/psen_scan_v2/doc/README.md, line 2), Skipping current block!
/home/alex/catkin_ws_rosdoc_ci/src/psen_scan_v2/standalone/README.md:1: warning: found more than one \mainpage comment block! (first occurrence: /home/alex/catkin_ws_rosdoc_ci/src/psen_scan_v2/doc/README.md, line 2), Skipping current block!
/home/alex/catkin_ws_rosdoc_ci/src/psen_scan_v2/standalone/include/psen_scan_v2_standalone/communication_layer/udp_client.h:64: warning: unable to resolve reference to 'RawData' for \ref command
```

Minor fixes for docu generation

---

.github/workflows/ci_rosdoc_lite_check.yml
.rosdoc_lite_check.sh
.rosdoc_lite_ignore

Needs 
**Add rosdoc_lite into CI**
The file `.rosdoc_lite_ignore` is needed since some warnings would need to be fixed upstream (e.g. https://github.com/ros-infrastructure/rosdoc_lite/pull/100) , yet it seems there is not much activity going on in https://github.com/ros-infrastructure/rosdoc_lite
Eventually this could be added to https://github.com/PilzDE/industrial_ci_addons or even https://github.com/ros-industrial/industrial_ci

Check rosdoc_lite for errors in CI

---

standalone/include/psen_scan_v2_standalone/scan_range.h
standalone/test/unit_tests/util/unittest_scan_range.cpp

Fix wrong behavior when angle start equal angle end

---

standalone/README.md

clarifications for headless boost

---

CMakeLists.txt
include/psen_scan_v2/ros_scanner_node.h
standalone/include/psen_scan_v2_standalone/util/logging.h
standalone/src/data_conversion_layer/start_request_serialization.cpp
standalone/test/integration_tests/api/integrationtest_scanner_api.cpp

Log scan range values requested from the scanner and the scan range actually published in the laser scan messages.

Inform user about current scan range

---

launch/psen_scan_v2.launch

Minor tweak of python expressions in launch-file. From http://wiki.ros.org/roslaunch/XML:
```
$(eval <expression>) allows to evaluate arbitrary complex python expressions.
```

Use python method for computing radians in launch-file

---

include/psen_scan_v2/ros_scanner_node.h
standalone/src/data_conversion_layer/start_request_serialization.cpp

Fixes #197
Example output:
```
[ INFO] [1621505253.525208180]: Publishing laser scan with angle_min=-137.2 angle_max=-137.0 angle_increment=0.1 degrees. 1 angle values.
```
Not that urgent, I guess.

Add format string for output of decimal numbers

---

.github/workflows/ci_action_standalone.yml

Fixes issues with the standalone build. Could be related to some cmake update I guess...
See for example:
https://github.com/PilzDE/psen_scan_v2/runs/2762716878?check_suite_focus=true
<skip>

Fix ubuntu standalone ci

---

standalone/test/integration_tests/api/integrationtest_scanner_api.cpp

Improves the readability of the integrationtests.

Improve integration test readability

---

standalone/test/include/psen_scan_v2_standalone/util/integrationtest_helper.h
standalone/test/integration_tests/api/integrationtest_scanner_api.cpp

These changes represent a minor improvement of the readability of the `integrationtest_scanner_api`.

Refactor integrationtest scanner api

---

standalone/test/include/psen_scan_v2_standalone/util/integrationtest_helper.h
test/hw_tests/hwtest_scan_compare.cpp
test/include/psen_scan_v2/laserscan_validator.h

These changes fix the `integrationtest_scanner_api` and the `hwtest_scan_compare`.

Fix minor test issues

---

README.md

Document possiblilities to get the scan data as soon as possible

Add speed optimization notes to readme

---

standalone/test/integration_tests/api/integrationtest_scanner_api.cpp

These changes improve the readability of the integration tests
These changes fix a test, that was missing the barrier for the scanner mock.
---
<details>
</details>

Remove Nice scanner mock from api integration test

---

standalone/test/integration_tests/api/integrationtest_scanner_api.cpp

These changes Fix #240
I figured out that the problem was present in two test cases.
---
<details>
</details>

Add missing barriers in integrationtest_scanner_api. Fixes #240

---

CHANGELOG.rst
CMakeLists.txt
standalone/test/unit_tests/util/unittest_tenth_of_degree.cpp
test/hw_tests/hwtest_scan_compare.cpp
test/hw_tests/hwtest_scan_compare_standalone.cpp
test/include/psen_scan_v2/dist.h
test/include/psen_scan_v2/laserscan_validator.h

Always build hardware tests to ensure no changes are introduced that build-break them.
---
<details>
</details>

Always build hardware tests

---

standalone/test/integration_tests/api/integrationtest_scanner_api.cpp

These changes improve the readability of the `integrationtest_scanner_api`.
Here we only target the `std::async` usage and don't care about expectations being in sub-functions.
---
<details>
</details>

Refactor std::async usage in integrationtest_scanner_api

---

test/integration_tests/integrationtest_config_server_node.cpp

These changes reduce the tests of the msg content to a single test case with a more descriptive matcher.
To give an example, changing the `frame_id` of the second zoneset leads to the following output (shortened):
```
[ RUN      ] ConfigServerNodeTest.shouldPublishMessageMatchingExpectedZoneSetConfig
unknown file: Failure
Unexpected mock function call - returning directly.
Function call: callback(@0x7eff537fd990 96-byte object <C0-10 00-48 FF-7E 00-00 A0-10 00-48 FF-7E 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 F0-D8 91-2D 8E-55 00-00 E0-21 00-4C FF-7E 00-00 B7-FD 78-61 E2-95 3C-15 00-10 00-48 FF-7E 00-00 81-7F B8-2B 8E-55 00-00 18-C9 6D-95 FE-7F 00-00 18-C9 6D-95 FE-7F 00-00 00-00 00-00 00-00 00-00>)
Google Mock tried the following 1 expectation, but it didn't match: …
```

Refactor zoneset matchers

---

standalone/test/include/psen_scan_v2_standalone/util/expectations.h

Fix indentation Error

---

src/psen_scan_driver.cpp
standalone/test/integration_tests/api/integrationtest_scanner_api.cpp

These changes Remove an unneccessary async call from the driver node and therefore reduce complexity.
---
<details>
</details>

Remove unneccessary async call from driver node

---

CHANGELOG.rst
CMakeLists.txt
include/psen_scan_v2/ros_scanner_node.h
standalone/include/psen_scan_v2_standalone/configuration/scanner_ids.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/diagnostics.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/laserscan_conversions.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/monitoring_frame_deserialization.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/start_request.h
standalone/include/psen_scan_v2_standalone/laserscan.h
standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine.h
standalone/include/psen_scan_v2_standalone/protocol_layer/scanner_state_machine_def.h
standalone/include/psen_scan_v2_standalone/scan_range.h
standalone/include/psen_scan_v2_standalone/scanner_config_builder.h
standalone/include/psen_scan_v2_standalone/scanner_v2.h
standalone/include/psen_scan_v2_standalone/util/watchdog.h
standalone/src/data_conversion_layer/diagnostics.cpp
standalone/src/data_conversion_layer/monitoring_frame_deserialization.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_monitoring_frame_serialization_deserialization.cpp
test/include/psen_scan_v2/dist.h
test/include/psen_scan_v2/laserscan_validator.h
test/include/psen_scan_v2/ros_integrationtest_helper.h

These changes Fix #277
---
<details>
</details>

Apply clang-tidy fixes to header-files.

---

launch/bringup.launch.xml

Remove unsupported required attribute in bringup.launch.xml

---

README.md

* Remove experimental status and restore previous installation notes
* Add foxy build status
* Add note on ros2 branch and versioning

Update README.md after Foxy release

---

include/psen_scan_v2/io_state_ros_conversion.h
msg/IOState.msg
standalone/include/psen_scan_v2_standalone/data_conversion_layer/io_pin_data.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/laserscan_conversions.h
standalone/include/psen_scan_v2_standalone/io_state.h
standalone/src/data_conversion_layer/monitoring_frame_deserialization.cpp
standalone/test/include/psen_scan_v2_standalone/communication_layer/udp_frame_dumps.h
standalone/test/include/psen_scan_v2_standalone/data_conversion_layer/io_pin_data_helper.h
standalone/test/include/psen_scan_v2_standalone/util/gtest_expectations.h
standalone/test/include/psen_scan_v2_standalone/util/matchers_and_actions.h
standalone/test/src/data_conversion_layer/monitoring_frame_serialization.cpp
standalone/test/unit_tests/api/unittest_io_state.cpp
standalone/test/unit_tests/api/unittest_laserscan.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_laserscan_conversions.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_monitoring_frame_msg.cpp
standalone/test/unit_tests/data_conversion_layer/unittest_monitoring_frame_msg_stamped.cpp
test/hw_tests/hwtest_io_state.cpp
test/include/psen_scan_v2/ros_integrationtest_helper.h
test/integration_tests/integrationtest_ros_scanner_node.cpp
test/unit_tests/unittest_io_state_rosconversions.cpp

These changes should give a simpler and more consistent naming of input/output methods/member variables.
---
<details>
When we decide the i/o-feature is ready.
</details>

Rename logical_input to input (except for deserialization)

---

CHANGELOG.rst
README.md
package.xml

Prepare release

---

README.md

Add prior version info to readme

---

README.md

backports build status and description of ros2 branch from PR #287
to main

BACKPORT: update README

---

CHANGELOG.rst
package.xml

Prepare fix release

---

CHANGELOG.rst
standalone/include/psen_scan_v2_standalone/data_conversion_layer/io_constants.h
standalone/include/psen_scan_v2_standalone/data_conversion_layer/io_state_conversions.h
standalone/test/include/psen_scan_v2_standalone/util/gtest_expectations.h
standalone/test/unit_tests/data_conversion_layer/unittest_io_state_conversions.cpp

These changes Fix #321. Confirmed with hardware.
---
<details>
</details>

Ignore changes of unused IOs

---

.github/workflows/ci_action_win_standalone.yml

Also using windows-2019 for ros2
